-- Active: 1720035729684@@localhost@5432@algoritma
CREATE SCHEMA IF NOT EXISTS denormalized;
CREATE SCHEMA IF NOT EXISTS dimensional;
CREATE SCHEMA IF NOT EXISTS bronze;
CREATE SCHEMA IF NOT EXISTS silver;
CREATE SCHEMA IF NOT EXISTS gold;